name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CLANG_TIDY: true

jobs:
  test:
    name: Test Implementation
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64

    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [jazzy, kilted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ROS Industrial CI
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          CXXFLAGS: -Wall -Wextra -Wpedantic
          CLANG_TIDY: false # Set to true once newer version of clang-tidy is available
