name: Tag & Release

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: 'If not specified, all packages will be released.'
        options:
          - ""
          - hydrodynamics

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        job:
          - runner: 2vcpu-ubuntu-2404
            arch: amd64
            ros_distro: jazzy
          - runner: 4vcpu-ubuntu-2404-arm
            arch: arm64
            ros_distro: jazzy

    name: Build - ${{ matrix.job.arch }} - ${{ matrix.job.ros_distro }}
    runs-on: ${{ matrix.job.runner }}

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Semantic release - Build
        uses: Greenroom-Robotics/ros_semantic_release_action@main
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          package: ${{ github.event.inputs.package }}
          arch: ${{ matrix.job.arch }}
          ros_distro: ${{ matrix.job.ros_distro }}
          github_release: false
          public: true
          changelog: false
          skip_build: false
          skip_tag: true
          release_branches: main

  release:
    name: Create Release
    runs-on: 2vcpu-ubuntu-2404
    needs:
      - build

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Release
        uses: Greenroom-Robotics/ros_semantic_release_action@main
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          package: ${{ github.event.inputs.package }}
          github_release: true
          public: true
          changelog: false
          skip_build: true
          skip_tag: false
          release_branches: main